### ISSUE TITLE
Error using Schmoo Branch

### ISSUE THREAD

**Issue by korang** [ChrisTruncer/EyeWitness#119]
Attempting to capture: https://199.38.150.2:443  (3/308)
Traceback (most recent call last):
  File "EyeWitness.py", line 2885, in <module>
    picture_name, ew_output_object, source_name)
  File "EyeWitness.py", line 1182, in selenium_capture
    headers = dict(urllib2.urlopen(requesting_object.return_remote_system_address()).info())
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1219, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer

**Comment by ChrisTruncer** [comment]
It's odd that you are hitting that error, but maybe you are resolving the page faster than I am.  I am running into a timeout when using that same url and it's skipping on to the next one.

However, I do believe I can now catch that error.  I just pushed the fix to this branch.  I believe this will fix it for you, but if for some reason it doesn't let me know and just repost in here.

Thanks again for reporting the issue, really helps me iron out and get rid of a lot of the issues I missed.  I appreciate it!
