### ISSUE TITLE
Schmoo Branch -- Error

### ISSUE THREAD

**Issue by korang** [ChrisTruncer/EyeWitness#122]
Attempting to capture: http://199.38.150.157:80  (207/308)
Attempting to capture: http://199.38.150.158:80  (208/308)
Attempting to capture: http://199.38.150.159:80  (209/308)
Traceback (most recent call last):
  File "./EyeWitness.py", line 2887, in <module>
    picture_name, ew_output_object, source_name)
  File "./EyeWitness.py", line 1190, in selenium_capture
    selenium_object.save_screenshot(capture_path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 696, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 715, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 725, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Could not convert screenshot to base64 - Error: Invalid base64 data: data:,
Stacktrace:
    at FirefoxDriver.prototype.screenshot (file:///tmp/tmpBAq6eH/extensions/fxdriver@googlecode.com/components/driver-component.js:9844:5)
    at DelayedCommand.prototype.executeInternal_/h (file:///tmp/tmpBAq6eH/extensions/fxdriver@googlecode.com/components/command-processor.js:11635:16)
    at DelayedCommand.prototype.executeInternal_ (file:///tmp/tmpBAq6eH/extensions/fxdriver@googlecode.com/components/command-processor.js:11640:7)
    at DelayedCommand.prototype.execute/< (file:///tmp/tmpBAq6eH/extensions/fxdriver@googlecode.com/components/command-processor.js:11582:5)

Hope I am not getting annoying.  Really love this program and wanting to use it to help better automate someting for my work.

**Comment by ChrisTruncer** [comment]
No, not getting annoying at all, I wanted input to see if there were errors, so thanks for sending all this info over.

**Comment by ChrisTruncer** [comment]
Ha, well you found a bug that I cannot seem to re-create.  I've tested against the URLs you've provided a couple times, but it seems to save fine for me each time (I'm running in Kali Linux).  I do see where I can potentially catch this issue, it happens when there is a problem (unknown why, library issue maybe?) saving the screenshot to disk.  I'm trying to just catch the error now and print out to the console that it happened.  It won't save that image to disk, but it catches it, reports the error, and continues on.  

If this doesn't catch it, or causes another issue, just let me know (I can't fully test the fix since I can't recreate it here).

Thanks again for letting me know, and keep any/all of the bug reports coming!
