### ISSUE TITLE
beta selenium fails with error

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#131]
I'm running this on a headless box so just had to install iceweasel to make selenium happy but even after that I get this error:

```
Traceback (most recent call last):
  File "./EyeWitness.py", line 2857, in <module>
    selenium_object = create_selenium_driver(cli_parsed)
  File "./EyeWitness.py", line 341, in create_selenium_driver
    driver = webdriver.Firefox(profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 66, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 100, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by ChrisTruncer** [comment]
This shouldn't be an issue anymore I believe.  Thanks!
