### ISSUE TITLE
ssl.CertificateError: hostname '12.3.4' doesn't match 'xxx.com'

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#132]
Installed the beta on a normal machine and got this error:

```
Traceback (most recent call last):
  File "./EyeWitness.py", line 2910, in <module>
    picture_name, ew_output_object, source_name)
  File "./EyeWitness.py", line 1194, in selenium_capture
    headers = dict(urllib2.urlopen(requesting_object.return_remote_system_address()).info())
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1001, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 796, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 273, in match_hostname
    % (hostname, dnsnames[0]))
ssl.CertificateError: hostname '12.3.4' doesn't match 'xxx.com'

**Comment by ChrisTruncer** [comment]
ok.  We're re-writing this in a "nuke_it_all" branch.  This is a ground-up re-write.  Ideally, we won't run into this.  I'm leaving this open so we can try to catch it.  Also, if you happen to have a sample public URL we could use to test this, then that would help.

**Comment by digininja** [comment]
I was running it on an internal system so can't give you anything but if I
see it on an external I'll send you a link.

**Comment by rvazarkar** [comment]
As far as I know, this issue should be resolved in the new branch, but let me know if you run into it again

**Comment by digininja** [comment]
Will do

**Comment by ChrisTruncer** [comment]
And we're merged!
