### ISSUE TITLE
Error unpacking pyvirtualdisplay

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#136]
Trying to install the latest nuke_it_all branch and got this error when running the setup:

```
[*] Installing Python Modules
Requirement already satisfied (use --upgrade to upgrade): python-qt-binding in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): fuzzywuzzy in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): selenium in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Downloading/unpacking pyvirtualdisplay
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 292, in find_requirement
    elif is_prerelease(version) and not (self.allow_all_prereleases or req.prereleases):
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prerelease
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x in parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log
Requirement already satisfied (use --upgrade to upgrade): python-Levenshtein in /usr/lib/python2.7/dist-packages
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/lib/python2.7/dist-packages
Cleaning up...

```

Running:

```
pip install pyvirtualdisplay
```
on its own gives the same error. Not your bug but do you have a work around?

The pip.log doesn't have anything particularly useful in it.

**Comment by digininja** [comment]
An apt-get update && apt-get dist-upgrade fixed it.

Might be worth adding that to the start of your script or maybe suggesting people do it so they don't get annoyed with you forcing it on them.

**Comment by ChrisTruncer** [comment]
Merged this in

**Comment by ChrisTruncer** [comment]
Thanks for the heads up!
