### ISSUE TITLE
Error in pickle

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#142]
Just got this from a freshly updated nuke_all branch. I ran it a second time and it worked OK so don't know what caused it.

````
Traceback (most recent call last):
  File "./EyeWitness.py", line 547, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 475, in multi_mode
    results = dbm.get_complete_http()
  File "/home/robin/tools/web/EyeWitness/modules/db_manager.py", line 141, in get_complete_http
    o = pickle.loads(str(row['object']))
  File "/usr/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\x00'

**Comment by rvazarkar** [comment]
Any chance you can share the url it broke on?

**Comment by digininja** [comment]
Drop me a mail and I'll send it over.

**Comment by ChrisTruncer** [comment]
@rvazarkar @digininja is this still an open issue?

**Comment by digininja** [comment]
Only happened once for me during onsite job, don't know if fixed or not

**Comment by rvazarkar** [comment]
I was unable to reproduce the issue personally, so until I can repro it
going to be hard to figure out a fix

**Comment by digininja** [comment]
OK, close it and I'll reopen it if it happens again.
