### ISSUE TITLE
Errors when attempting VNC/RDP scan

### ISSUE THREAD

**Issue by schristiaens** [ChrisTruncer/EyeWitness#151]
I've got a scan that fails whenever it starts the VNC/RDP requests.  If I run it with --all, it successfully gets through the web checks, but then fails.  If I just run --rdp, if fails immediately.  I'm running on the most recent Kali.  Here is the trace it gives:

Starting VNC/RDP Requests (1977 Hosts)
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali32
_IceTransSocketUNIXConnect: Cannot connect to non-local host kali32
Qt: Session management error: Could not open network socket
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 413, in fireEvent
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 301, in addCallback
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 290, in addCallbacks
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 551, in _runCallbacks
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 426, in _continueFiring
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1164, in _reallyStartRunning
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 295, in _handleSignals
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 205, in __init__
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 138, in __init__
    
exceptions.OSError: [Errno 24] Too many open files
Unhandled Error
Traceback (most recent call last):
  File "./EyeWitness.py", line 562, in <module>
    
  File "./EyeWitness.py", line 485, in multi_mode
    
  File "/usr/local/lib/python2.7/dist-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 240, in _qt_timeout
    
  File "/usr/local/lib/python2.7/dist-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 246, in _iterate
    
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 800, in runUntilCurrent
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 364, in resolveAddress
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 566, in resolve
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 267, in getHostByName
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 965, in getThreadPool
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 930, in _initThreadPool

These last 6 lines repeat over and over, possibly once for each host in my long list.

Thanks.

**Comment by ChrisTruncer** [comment]
How many hosts are you attempting to scan at once?  We may need to split the hosts that are scanned at once in the code.

**Comment by rvazarkar** [comment]
This is almost definitely because of the open socket limitation which is
extremely annoying.  Still not sure how to work around it other than
splitting the host list up and doing it one at a time

**Comment by schristiaens** [comment]
I was trying to scan close to 2000 hosts.  The web scan had no problem with
that size, but I would understand if that was more than might be expected.

**Comment by rvazarkar** [comment]
The web scan does stuff in parallel, but no more than 10 connections are opened at a time. Unfortunately, we haven't figured out how to do the same with VNC/RDP yet. Twisted pretty much just fires off everything at once which will very quickly kill your max sockets.

**Comment by ChrisTruncer** [comment]
I'm going to go ahead and close this for the time being.  If you still encounter issues, please let us know.
