### ISSUE TITLE
I can't get EyeWitness to Work

### ISSUE THREAD

**Issue by sawzeeyy** [ChrisTruncer/EyeWitness#228]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali Sana 2.0 on VMware running on a Windows 8 x64

## Pastebin link to error you are encountering
````
################################################################################
#                                  EyeWitness                                  #
################################################################################

Traceback (most recent call last):
  File "./EyeWitness.py", line 605, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 431, in multi_mode
    display = Display(visible=0, size=(1920, 1080))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error! 

````

**Comment by ChrisTruncer** [comment]
Did you run the setup script? Can you show that output on a paste in link?

**Comment by kuskumar** [comment]
You need to install 'Xvfb'. Execute below commands: 
apt-get install dpkg --configure -a
apt-get install Xvfb

**Comment by sawzeeyy** [comment]
Thanks 😊

**Comment by rajeshk28** [comment]
/EyeWitness/Python# apt-get install Xvfb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package Xvfb
------------------------------------------------------------
when tryin to insall Xvfb this givens above error
-------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 169, in start
    cmd, stdout=stdout, stderr=stderr, cwd=self.cwd, env=self.env,
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb': 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./EyeWitness.py", line 421, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 332, in multi_mode
    display = Display(visible=0, size=(1920, 1080))
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/display.py", line 63, in __init__
    **kwargs
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/xvfb.py", line 50, in __init__
    manage_global_env=manage_global_env,
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/abstractdisplay.py", line 88, in __init__
    helptext = get_helptext(program)
  File "/usr/local/lib/python3.7/dist-packages/pyvirtualdisplay/util.py", line 10, in get_helptext
    p.call()
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 141, in call
    self.start().wait(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/easyprocess/__init__.py", line 174, in start
    raise EasyProcessError(self, "start error")
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb': 'Xvfb' return_code=None stdout="None" stderr="None" timeout_happened=False>
------------------------------------------------------------------------------------------------------------------------------------
This is the main error...what should i do

**Comment by digininja** [comment]
Install xvfb not Xvfb
