### ISSUE TITLE
error: RDP Libraries not found - Fixed by manually installing automat

### ISSUE THREAD

**Issue by dascannibal** [ChrisTruncer/EyeWitness#239]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu 16.04 x64

## Pastebin link to error you are encountering
When trying to start ./EyeWitness after running the setup file I get
[*] RDP libraries not found.
[*] Please run the script in the setup directory!

## Expected behavior (vs. what you encountered)
software doesn't start.

## Any additional information

I was able to fix this by:
pulling down the rdpy github repo and from that directory...
pip install automat
python setup.py install

It seems that the rdpy setup file is referencing a URL that no longer contains the needed files. Installing automat and then rerunning the rdpy setup seems to have resolved the issue.

**Comment by gulaschskanone** [comment]
Have the same issue, but your workflow doesn't fixed it for me.

**Comment by rapliandras** [comment]
pip install rdpy -U

fixes this.

**Comment by ChrisTruncer** [comment]
I'll see if I can download Ubuntu (currently traveling), but I have jsut tested this on Kali and Debian and haven't been able to reproduce this.

But I'll specifically test Ubuntu once I can download an iso to validate that.

**Comment by ChrisTruncer** [comment]
I can't recreate this issue on my end. It seems everything is installing when running the setup script on an Ubuntu 16.04 host

**Comment by BBerastegui** [comment]
It'll be great to re-open this. I was able to reproduce the same problem by running in a debian:latest docker container. The setup.sh installs everything but this:

`pip install six -U
pip install rdpy`

Was also fixed by doing that manually.

**Comment by ChrisTruncer** [comment]
does it work with that version of rdpy? I had to specifically modify the RDPY library and made some changes which is why it pulls that from my github.

**Comment by musashi242** [comment]
Ran the manual installs and still seem to get the same error.  Perhaps because I have a newer version of six?  How would I revert to 1.10?  Thanks.

[*] RDP libraries not found.
[*] Please run the script in the setup directory!

**Comment by ChrisTruncer** [comment]
Newer version of six?

**Comment by musashi242** [comment]
From the above, I thought it could be a version issue, but looks like not.  My six is sitting in /usr/lib/python2.7/dist-packages, if perhaps the path is the problem.

**Comment by 2clicks2late** [comment]
Running into the same problem on Kali rolling 2018.1
Tried all of the above.
pip install six -U result:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 487, in _prepare_file
    req_to_install, finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 428, in _check_skip_installed
    req_to_install, upgrade_allowed)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by ghsec** [comment]
On Ubuntu 16.04 I fix this problem with next steps.
Go to Eyewitness dir and open terminal.
1. sudo su
2. cd install
3. ./setup.sh

Now EyeWitness works well. U need be with Super user prevelige.

**Comment by akshaybrij** [comment]
I am getting error 
[*] RDP libraries not found.
[*] Please run the script in the setup directory!
I tried to manually install rdpy but still getting the error please help out here.

**Comment by TechByTom** [comment]
Another option for addressing this issue:
`pip install --ignore-installed six rdpy`

**Comment by akg87** [comment]
Running this tool on windows 10 and using python 2.7.15. Did everything suggested about but the issue still persist. Is there any hot fix for this problem?

**Comment by oliverloveless** [comment]
I'm not sure if this will help anyone, but maybe it will. I'm on ubuntu 16.05, python 2.7.something, and trying to install Eyewitness in a virtualenv. 
For me this was actually an issue with from PyQt4, when it imports in "modules/rdp_module.py". By deleting "lib/python2.7/no-global-site-packages.txt" from my virtualenv, I could use the module that was installed by the setup.sh script.

Otherwise I'd recommend as a starting point that everyone just try importing each of the modules imported in that "try" section in rdp_module.py from a python shell, and see if it's actually the rdp modules causing issues.
