### ISSUE TITLE
Python + TLS 1.1 issue

### ISSUE THREAD

**Issue by rapliandras** [ChrisTruncer/EyeWitness#249]
I can't seem to figure out this version mismatch issue. Do you have a clue for this?
Fresh install after running setup.py

```

Traceback (most recent call last):
  File "EyeWitness.py", line 16, in <module>
    from modules import rdp_module
  File "/tmp/EyeWitness/modules/rdp_module.py", line 7, in <module>
    from rdpy.protocol.rdp import rdp
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/rdp.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/rdpy/protocol/rdp/x224.py", line 313, in <module>
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/ssl.py", line 65, in <module>
    from twisted.internet import tcp, interfaces
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.1.0-py2.7-linux-x86_64.egg/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

```

**Comment by ChrisTruncer** [comment]
I'm not sure if this is a local conflict with something already installed, but I haven't run across that error before.

**Comment by ChrisTruncer** [comment]
Were you able to figure this out?

**Comment by rapliandras** [comment]
No. Is graphical runlevel a requirement?

**Comment by rapliandras** [comment]
Okay. I upgraded rdpy library and it now works fine.

    pip install rdpy -U

(add this to the setup script please. :) )
