### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base

### ISSUE THREAD

**Issue by kawaxi** [ChrisTruncer/EyeWitness#265]
## OS Used - ALL Information (architecture, linux flavor, etc.)

Linux kali 4.9.0-kali4-amd64 #1 SMP Debian 4.9.25-1kali1 (2017-05-04) x86_64 GNU/Linux

## Pastebin link to error you are encountering

./EyeWitness.py
Traceback (most recent call last):
  File "./EyeWitness.py", line 13, in <module>
    from modules import db_manager
  File "/root/EyeWitness/modules/db_manager.py", line 4, in <module>
    from objects import HTTPTableObject
  File "/root/EyeWitness/modules/objects.py", line 5, in <module>
    from helpers import strip_nonalphanum
  File "/root/EyeWitness/modules/helpers.py", line 15, in <module>
    from login_module import checkCreds
  File "/root/EyeWitness/modules/login_module.py", line 8, in <module>
    from bs4 import BeautifulSoup as beatsop
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

## Expected behavior (vs. what you encountered)
didn't run

**Comment by ChrisTruncer** [comment]
I just tested this on the latest version of Kali (on a new VM) and everything is working out of the box

**Comment by ChrisTruncer** [comment]
Closing due to no response

**Comment by 0xhaggis** [comment]
I got exactly the same error on a fully updated Kali box today. To fix it I ran:

`pip install --upgrade beautifulsoup4`
`pip install --upgrade html5lib`

Eyewitness works correctly now.
