### ISSUE TITLE
Does not handle international utf8 characters

### ISSUE THREAD

**Issue by jabjorkhaug** [ChrisTruncer/EyeWitness#269]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali linux

## Error:

Traceback (most recent call last):
  File "EyeWitness.py", line 612, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness.py", line 546, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/tools/EyeWitness/modules/reporting.py", line 198, in sort_data_and_write
    html += obj.create_table_html()
  File "/tools/EyeWitness/modules/objects.py", line 240, in create_table_html
    self.sanitize(key), self.sanitize(value))
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 56: invalid start byte

## Expected behavior (vs. what you encountered)
It should work..

## Any additional information
See screenshot
![image](https://user-images.githubusercontent.com/29369899/27023633-b0975928-4f53-11e7-80fd-6c1525ed45be.png)

**Comment by ChrisTruncer** [comment]
Can you give me the URL which is causing this issue?

**Comment by ChrisTruncer** [comment]
This should now be fixed, can you validate?

**Comment by jabjorkhaug** [comment]
It now works! :) thanks!!!
