### ISSUE TITLE
HTTPTableObject error

### ISSUE THREAD

**Issue by g1ldedm1n1on** [ChrisTruncer/EyeWitness#285]
## OS Used - Kali Rolling

Traceback (most recent call last):
  File "EyeWitness.py", line 612, in <module>
    multi_mode(cli_parsed)
  File "EyeWitness.py", line 546, in multi_mode
    sort_data_and_write(cli_parsed, results)
  File "/opt/EyeWitness/modules/reporting.py", line 200, in sort_data_and_write
    html += obj.create_table_html()
  File "/opt/EyeWitness/modules/objects.py", line 238, in create_table_html
    for key, value in self.headers.items():
  File "/opt/EyeWitness/modules/objects.py", line 134, in headers
    return self._headers
AttributeError: 'HTTPTableObject' object has no attribute '_headers'

**Comment by ChrisTruncer** [comment]
I've installed this on Kali and I do not encounter this issue. Additionally, you haven't provided any information on how to re-create this issue. For future issues, please provide all the information requested to allow me to help troubleshoot.

**Comment by okiwoki** [comment]
I'm having this exact same issue. I'll open a new ticket.
