### ISSUE TITLE
pip cryptography dependency problem

### ISSUE THREAD

**Issue by digininja** [ChrisTruncer/EyeWitness#287]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Kali x64 fully updated

## The bug
Running the setup, I got this error for each of the pip install lines
```
[*] Installing Python Modules
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')  
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
    libraries=libraries,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 39, in build_ffi
    ffi = cffi.FFI()
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 0.8.6 != 1.2.1
```

To fix it I uninstalled the Kali package python-cffi, did a apt-get update and upgrade then reinstalled the package. I then ran

```
easy_install -U cffi
```

After that the pip installs all worked fine and the setup completes. Don't know if all those steps are required but it fixed it for me.

If I hadn't been paying attention I'd probably have missed that the pip installs failed, it may be worth adding something into the setup script that checks the return code and either stops or flags up a warning if the install doesn't work correctly.

**Comment by ChrisTruncer** [comment]
That's really odd. Any way to re-test this? I have a clean kali image I do my testing from and everything just installed.

**Comment by digininja** [comment]
Can't think of one. This box has been around for quite  while and so the
versions of things may have slipped a little if dependencies have changed.
I've not had it on any other box.

Probably best to close this but hopefully it will get indexed so if anyone
else has the problem this should solve it for them.

**Comment by ChrisTruncer** [comment]
Agreed,

Some dependencies did get modified recently, it's possible that that might be causing it. But I do plan on leaving this here in the event anyone else encounters this. Thanks for letting me know
