### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by sdcampbell** [ChrisTruncer/EyeWitness#295]
Kali Linux 2017.2

Command line: "python /opt/EyeWitness/EyeWitness.py --headless --all-protocols -f nmap_scan.xml --no-prompt -d ./EyeWitness"

Output:
Traceback (most recent call last):
  File "./EyeWitness.py", line 624, in <module>
    multi_mode(cli_parsed)
  File "./EyeWitness.py", line 438, in multi_mode
    dbm.create_vnc_rdp_object('rdp', rdp, cli_parsed)
  File "/opt/EyeWitness/modules/db_manager.py", line 167, in create_vnc_rdp_object
    port = int(port)
ValueError: invalid literal for int() with base 10: '///usr/bin/../share/nmap/nmap.xsl" type="text/xsl"?>'

**Comment by ChrisTruncer** [comment]
You need to use -x with xml
