### ISSUE TITLE
Traceback when processing large lists of subdomains

### ISSUE THREAD

**Issue by phr0nak** [ChrisTruncer/EyeWitness#296]
## OS Used - ALL Information (architecture, linux flavor, etc.)
Ubuntu 17.10 (Artful Aardvark)
Kernel: 4.13.0-17-generic #20-Ubuntu

## Error you are encountering

`Traceback (most recent call last):
[*] Hit timeout limit when connecting to https://weblync.bitdefender.com, retrying
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "EyeWitness.py", line 352, in worker_thread
    manager.update_http_object(http_object)
  File "/EyeWitness/modules/db_manager.py", line 99, in update_http_object
    (o, True, http_object.id))
OperationalError: database is locked`

## Any additional information

The command used is: 
`./EyeWitness.py -d /tmp/report --no-prompt --no-dns --threads 100 -f /tmp/urls.txt --prepend-https --headless`

The number of subdomains is 297 (594 checks in total for http and https).

**Comment by ChrisTruncer** [comment]
That almost looks like a race condition because you have so many threads active trying to write to the database. If you lower the tread count, does it still error?

**Comment by phr0nak** [comment]
Definitely a race condition. With 10 threads (default value) all runs ok. Do you have any idea how high you could go here?

**Comment by ChrisTruncer** [comment]
Honestly, no idea. I’ve not tried running with that many threads. I usually do 5-10.

**Comment by phr0nak** [comment]
@ChrisTruncer Running EyeWitness against a large list of subdomains and 5 threads, I've got a new traceback.

<img width="501" alt="screen shot 2017-11-26 at 4 06 25 pm" src="https://user-images.githubusercontent.com/4283403/33241315-e556431a-d2c3-11e7-8f7e-1c3e4d6ae0ee.png">

Any idea if this is related?

**Comment by ChrisTruncer** [comment]
That looks to be a new error, any way to recreate that consistently?

**Comment by ChrisTruncer** [comment]
Bump

**Comment by arisada** [comment]
Same problem here:

```
root@ov-3555fc:~/EyeWitness# ./EyeWitness.py --active-scan --all-protocols -x ../quick_scan.xml --threads 1 --no-prompt
...
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1128, in connectionFailed

  File "/home/ubuntu/EyeWitness/modules/rdp_module.py", line 95, in clientConnectionFailed

  File "/home/ubuntu/EyeWitness/modules/db_manager.py", line 190, in update_vnc_rdp_object

sqlite3.OperationalError: database is locked

Unhandled Error
Traceback (most recent call last):
  File "./EyeWitness.py", line 624, in <module>

  File "./EyeWitness.py", line 543, in multi_mode

  File "/usr/local/lib/python2.7/dist-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 131, in write

--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 103, in callWithLogger

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/python/log.py", line 86, in callWithContext

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 122, in callWithContext

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/python/context.py", line 85, in callWithContext

  File "/usr/local/lib/python2.7/dist-packages/qt4reactor-1.6-py2.7.egg/qtreactor/qt4base.py", line 128, in _write

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/posixbase.py", line 258, in _disconnectSelectable

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 473, in connectionLost

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/tcp.py", line 450, in failIfNotConnected

  File "/usr/local/lib/python2.7/dist-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1128, in connectionFailed

  File "/home/ubuntu/EyeWitness/modules/rdp_module.py", line 93, in clientConnectionFailed

  File "/home/ubuntu/EyeWitness/modules/db_manager.py", line 45, in open_connection

sqlite3.OperationalError: unable to open database file

^C
Resume using ./EyeWitness.py --resume /home/ubuntu/EyeWitness/01032018_105626/ew.db
```

Either it's not a race or EyeWitness ignores the "--threads" parameter.

**Comment by ChrisTruncer** [comment]
For threads, I believe that is only used when scanning via http or https and not vnc or RDP

**Comment by ChrisTruncer** [comment]
At this point, I do not believe this is something I will be able to fix. My suggestion would be to run with less threads to not have multiple threads attempting to access the same resource. But please feel free to comment if there's anything related to this I can look into.
